
FROM python:3.13.0b3-alpine3.20

WORKDIR /app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# CMD [ "python", "./app.py" ]

# ENTRYPOINT ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

ENTRYPOINT uvicorn app:app --host 0.0.0.0 --reload
